version: '2'
services:
  run-import:
    build:
      context: ./run-import
      dockerfile: Dockerfile
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:0.13-alpine
    restart: always
    ports:
      - "8083:8083"   # HTTP API port
      - "8086:8086"   # Administrator interface port
